In [1]:
import numpy

In [2]:
configuracion_1=open('config_2.txt','r')
aux_atom=open('aux_atom.txt','w')
aux_drude=open('aux_drude.txt','w')
for line in configuracion_1:
    line_1=line.split()
    #print(line_1)
    if line_1[2]=='1': #atomo
        atomo='{0} {1} {2}\n'.format(line_1[3],line_1[4],line_1[5])
        aux_atom.write(atomo)
    if line_1[2]=='2': #drude
        drude='{0} {1} {2}\n'.format(line_1[3],line_1[4],line_1[5])
        aux_drude.write(drude)
aux_atom.close()
aux_drude.close()
configuracion_1.close()     

In [3]:
aux_read_atomo=open('aux_atom.txt','r')
aux_read_drude=open('aux_drude.txt','r')

Atom_Espacio=numpy.loadtxt(aux_read_atomo)
Drude_Espacio=numpy.loadtxt(aux_read_drude)

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
print('Atom:',Atom_Espacio)
print('Drude:',Drude_Espacio)
Centro_Espacio=(Drude_Espacio + Atom_Espacio)/2
print('centro:',Centro_Espacio)

print('numero de atomos',len(Drude_Espacio[:,0]))

Atom: [[488.952  485.739   47.1567]
 [ 15.0702 485.759   47.1678]
 [ 17.7486 485.76    47.309 ]
 ...
 [484.229  484.566   47.0408]
 [486.912  484.574   47.1978]
 [488.261  484.564   47.2104]]
Drude: [[488.953  485.739   47.1563]
 [ 15.0717 485.761   47.1673]
 [ 17.7486 485.758   47.3086]
 ...
 [484.23   484.565   47.0403]
 [486.911  484.576   47.1974]
 [488.259  484.564   47.2113]]
centro: [[488.9525  485.739    47.1565 ]
 [ 15.07095 485.76     47.16755]
 [ 17.7486  485.759    47.3088 ]
 ...
 [484.2295  484.5655   47.04055]
 [486.9115  484.575    47.1976 ]
 [488.26    484.564    47.21085]]
numero de atomos 95816


In [6]:
#verificación que atomos de C y drude se encuentren dentro del Radio de Van der Waals.

#d1:distancia entre centro y drude
#d2:distancia entre centro y atomo de C

d1= abs(Drude_Espacio - Centro_Espacio)
d2= abs(Centro_Espacio - Atom_Espacio)

In [7]:
#d2 #x listo, y listo, z listo

for i in range(95816):
    if d2[i,2]>1.7:
        print(i)
        print(d2[i,0])
        print('atomo_queda_fuera_de_RdVW')

In [8]:
#d1 #x listo, y listo, z listo

for i in range(95816):
    if d1[i,2]>1.7:
        print(i)
        print(d1[i,0])
        print('atomo_queda_fuera_de_RdVW')

In [9]:
#Luego de la Verificación se procede a crear archivos pqr y xyzr para generar mallas de grafeno.

In [10]:
#generar archivo.pqr a partir de datos originales de membrana de grafeno. En este caso configuracion 2
pqr_grafeno=open('grafeno_config_2.pqr','w')
configuracion_1=open('config_2.txt','r')

q_atomo='-0.26'
q_drude='0.26'
q_centro='0'
r_atomo='0'
r_drude='0'
r_centro='1.7'

for line in configuracion_1:
    line_1=line.split()
    if line_1[2]=='1':
        pqr_line='ATOM   '+str(line_1[0])+'  A  A  111  '+str(line_1[3])+'  '+str(line_1[5])+'  '+str(line_1[4])+'  '+q_atomo+'  '+r_atomo+'\n'
        pqr_grafeno.write(pqr_line)
    if line_1[2]=='2':
        pqr_line='ATOM   '+str(line_1[0])+'  A  A  112  '+str(line_1[3])+'  '+str(line_1[5])+'  '+str(line_1[4])+'  '+q_drude+'  '+r_drude+'\n'
        pqr_grafeno.write(pqr_line)

for i in range(95816):
    pqr_line= pqr_line='ATOM   '+str(95816*2+i+1)+'  A  A  113  '+str(Centro_Espacio[i,0])+'  '+str(Centro_Espacio[i,2])+'  '+str(Centro_Espacio[i,1])+'  '+q_centro+'  '+r_centro+'\n'
    pqr_grafeno.write(pqr_line)
    
pqr_grafeno.close()

In [11]:
#generar archivo.xyzr a partir de pqr de grafeno
pqr_grafeno_read=open('grafeno_config_2.pqr','r')
xyzr_grafeno=open('grafeno_config_2.xyzr','w')

for line in pqr_grafeno_read:
    line_1=line.split()
    if line_1[4]=='113':
        xyzr_line=str(line_1[5])+' '+str(line_1[6])+' '+str(line_1[7])+' '+str(line_1[9])+'\n'
        xyzr_grafeno.write(xyzr_line)
xyzr_grafeno.close()

In [12]:
#generar archivo.pqr de membrana de grafeno para vizualizacion
#La diferencia de este pqr con el anterior es que solo posee los atomos que tienen radio distinto de 0.

pqr_grafeno_vizualizacion=open('grafeno_config_2_vizualizacion.pqr','w')
configuracion_1=open('config_2.txt','r')

q_atomo='-0.26'
q_drude='0.26'
q_centro='0'
r_atomo='0'
r_drude='0'
r_centro='1.7'

for i in range(95816):
    pqr_line= pqr_line='ATOM   '+str(i)+'  C6  ALA  113  '+str(Centro_Espacio[i,0])+'  '+str(Centro_Espacio[i,2])+'  '+str(Centro_Espacio[i,1])+'  '+q_centro+'  '+r_centro+'\n'
    pqr_grafeno_vizualizacion.write(pqr_line)
    
pqr_grafeno_vizualizacion.close()

In [13]:
#debido a que la membrana de grafeno se encuentra en cualquier parte del espacio, es necesario
#trasladar cada uno de los atomos a una distancia que permita una manipulación mas facil.
#es por esto que se centra aproximadamente en x=0, z=0, y  la "cara superior" en y=0.

In [14]:
#traslacion pqr
#atomo
Centro_x_atom=(max(Atom_Espacio[:,0]) + min(Atom_Espacio[:,0]))/2
Centro_y_atom=max(Atom_Espacio[:,2])
Centro_z_atom=(max(Atom_Espacio[:,1]) + min(Atom_Espacio[:,1]))/2
print('centro_x_atom:',Centro_x_atom,'centro_y_atom:',Centro_y_atom,'centro_z_atom:',Centro_z_atom)
#Drude
Centro_x_drude=(max(Drude_Espacio[:,0]) + min(Drude_Espacio[:,0]))/2
Centro_y_drude=max(Drude_Espacio[:,2])
Centro_z_drude=(max(Drude_Espacio[:,1]) + min(Drude_Espacio[:,1]))/2
print('centro_x_drude:',Centro_x_drude,'centro_y_drude:',Centro_y_drude,'centro_z_drude:',Centro_z_drude)
#Centro_atom_drude
Centro_x_centro=(max(Centro_Espacio[:,0]) + min(Centro_Espacio[:,0]))/2
Centro_y_centro=max(Centro_Espacio[:,2]) 
Centro_z_centro=(max(Centro_Espacio[:,1]) + min(Centro_Espacio[:,1]))/2
print('centro_x_centro:',Centro_x_centro,'centro_y_centro:',Centro_y_centro,'centro_z_centro:',Centro_z_centro)

centro_x_atom: 251.34150000000002 centro_y_atom: 47.7052 centro_z_atom: 249.68745
centro_x_drude: 251.34095000000002 centro_y_drude: 47.7053 centro_z_drude: 249.68705
centro_x_centro: 251.341225 centro_y_centro: 47.70525 centro_z_centro: 249.68725


In [15]:
#generar archivo.pqr de membrana de grafeno: configuracion 2 trasladada a la posicion requerida.
#si se utiliza otra configuracion de la membrana de grafeno, cambiar valores de coordenadas de ATOM en base a
#los obtenidos en la casilla anterior.

pqr_grafeno_traslacion=open('grafeno_config_2_traslacion.pqr','w')
configuracion_1=open('config_2.txt','r')

q_atomo='-0.26'
q_drude='0.26'
q_centro='0'
r_atomo='0'
r_drude='0'
r_centro='1.7'

for line in configuracion_1:
    line_1=line.split()
    if line_1[2]=='1':
        pqr_line='ATOM   '+str(line_1[0])+'  A  A  111  '+str(float(line_1[3]) - 251.3415)+'  '+str(float(line_1[5]) - 47.7052 - 1.7)+'  '+str(float(line_1[4]) - 249.68745)+'  '+q_atomo+'  '+r_atomo+'\n'
        pqr_grafeno_traslacion.write(pqr_line)
    if line_1[2]=='2':
        pqr_line='ATOM   '+str(line_1[0])+'  A  A  112  '+str(float(line_1[3]) - 251.34095)+'  '+str(float(line_1[5]) - 47.7053 - 1.7)+'  '+str(float(line_1[4]) - 249.68705)+'  '+q_drude+'  '+r_drude+'\n'
        pqr_grafeno_traslacion.write(pqr_line)

for i in range(95816):
    pqr_line='ATOM   '+str(95816*2+i+1)+'  A  A  113  '+str(Centro_Espacio[i,0] - 251.341225)+'  '+str(Centro_Espacio[i,2] - 47.70525 - 1.7)+'  '+str(Centro_Espacio[i,1] - 249.68725)+'  '+q_centro+'  '+r_centro+'\n'
    pqr_grafeno_traslacion.write(pqr_line)
    
pqr_grafeno_traslacion.close()

In [16]:
#generar archivo.xyzr a partir de pqr de grafeno trasladada

pqr_grafeno_read_trasladada=open('grafeno_config_2_traslacion.pqr','r')
xyzr_grafeno_trasladada=open('grafeno_config_2_traslacion.xyzr','w')

for line in pqr_grafeno_read_trasladada:
    line_1=line.split()
    if line_1[4]=='113':
        xyzr_line=str(line_1[5])+' '+str(line_1[6])+' '+str(line_1[7])+' '+str(line_1[9])+'\n'
        xyzr_grafeno_trasladada.write(xyzr_line)
xyzr_grafeno_trasladada.close()

In [17]:
#generar archivo.pqr de membrana de grafeno para vizualizacion: configuracion 2 trasladada
#La diferencia de este pqr con el anterior es que solo posee los atomos que tienen radio distinto de 0.

pqr_grafeno_vizualizacion_tras=open('grafeno_config_2_vizualizacion_traslacion.pqr','w')
configuracion_1=open('config_2.txt','r')

q_atomo='-0.26'
q_drude='0.26'
q_centro='0'
r_atomo='0'
r_drude='0'
r_centro='1.7'

for i in range(95816):
    pqr_line= 'ATOM   '+str(i)+'  C  ALA  113  '+str(Centro_Espacio[i,0] - 251.341225)+'  '+str(Centro_Espacio[i,2] - 47.70525 - 1.7)+'  '+str(Centro_Espacio[i,1] - 249.68725)+'  '+q_centro+'  '+r_centro+'\n'
    pqr_grafeno_vizualizacion_tras.write(pqr_line)
    
pqr_grafeno_vizualizacion_tras.close()

In [18]:
#Eliminación de Archivos Auxiliares o No utiles.
from os import remove
remove("aux_atom.txt")
remove("aux_drude.txt")